import type { Player } from "./types";

export const careerPathByPlayerId: Record<string, string> = {
  "john-stones": "Barnsley -> Everton -> Manchester City",
  "marcus-rashford": "Manchester United academy -> Manchester United",
  "son-heung-min": "Hamburg -> Bayer Leverkusen -> Tottenham Hotspur -> Los Angeles FC",
  "kim-min-jae": "Jeonbuk Hyundai Motors -> Fenerbahce -> Napoli -> Bayern Munich",
  "lee-kang-in": "Valencia academy -> Mallorca -> Paris Saint-Germain",
  "hwang-hee-chan": "Red Bull Salzburg -> RB Leipzig -> Wolverhampton Wanderers",
  "edin-dzeko": "Wolfsburg -> Manchester City -> Roma -> Inter -> Fenerbahce -> Schalke",
  "alphonso-davies": "Vancouver Whitecaps -> Bayern Munich",
  "jonathan-david": "Gent -> Lille -> Juventus",
  "neymar": "Santos -> Barcelona -> Paris Saint-Germain -> Al Hilal -> Santos",
  "vinicius-junior": "Flamengo -> Real Madrid",
  "bruno-guimaraes": "Athletico Paranaense -> Lyon -> Newcastle United",
  "marquinhos": "Corinthians -> Roma -> Paris Saint-Germain",
  "achraf-hakimi": "Real Madrid -> Borussia Dortmund -> Inter -> Paris Saint-Germain",
  "andy-robertson": "Queen's Park -> Dundee United -> Hull City -> Liverpool",
  "scott-mctominay": "Manchester United academy -> Manchester United -> Napoli",
  "christian-pulisic": "Borussia Dortmund -> Chelsea -> Milan",
  "weston-mckennie": "Schalke -> Juventus",
  "arda-guler": "Fenerbahce -> Real Madrid",
  "florian-wirtz": "Koln academy -> Bayer Leverkusen -> Liverpool",
  "manuel-neuer": "Schalke -> Bayern Munich",
  "joshua-kimmich": "Stuttgart academy -> RB Leipzig -> Bayern Munich",
  "antonio-rudiger": "Stuttgart -> Roma -> Chelsea -> Real Madrid",
  "jamal-musiala": "Chelsea academy -> Bayern Munich",
  "moises-caicedo": "Independiente del Valle -> Brighton -> Chelsea",
  "frenkie-de-jong": "Willem II -> Ajax -> Barcelona",
  "memphis-depay": "PSV -> Manchester United -> Lyon -> Barcelona -> Atletico Madrid -> Corinthians",
  "wataru-endo": "Shonan Bellmare -> Urawa Red Diamonds -> Stuttgart -> Liverpool",
  "alexander-isak": "AIK -> Borussia Dortmund -> Real Sociedad -> Newcastle United -> Liverpool",
  "virgil-van-dijk": "Groningen -> Celtic -> Southampton -> Liverpool",
  "kevin-de-bruyne": "Genk -> Chelsea -> Werder Bremen -> Wolfsburg -> Manchester City -> Napoli",
  "romelu-lukaku": "Anderlecht -> Chelsea -> Everton -> Manchester United -> Inter -> Roma -> Napoli",
  "jeremy-doku": "Anderlecht -> Rennes -> Manchester City",
  "mohamed-salah": "Al Mokawloon -> Basel -> Chelsea -> Fiorentina -> Roma -> Liverpool",
  "omar-marmoush": "Wadi Degla -> Wolfsburg -> Stuttgart -> Eintracht Frankfurt -> Manchester City",
  "lamine-yamal": "Barcelona academy -> Barcelona",
  "pedri": "Las Palmas -> Barcelona",
  "rodri": "Villarreal -> Atletico Madrid -> Manchester City",
  "nico-williams": "Athletic Club academy -> Athletic Club",
  "dani-olmo": "Barcelona academy -> Dinamo Zagreb -> RB Leipzig -> Barcelona",
  "federico-valverde": "Penarol -> Real Madrid",
  "darwin-nunez": "Penarol -> Almeria -> Benfica -> Liverpool -> Al Hilal",
  "ronald-araujo": "Rentistas -> Boston River -> Barcelona",
  "kylian-mbappe": "Monaco -> Paris Saint-Germain -> Real Madrid",
  "ousmane-dembele": "Rennes -> Borussia Dortmund -> Barcelona -> Paris Saint-Germain",
  "aurelien-tchouameni": "Bordeaux -> Monaco -> Real Madrid",
  "mike-maignan": "Paris Saint-Germain academy -> Lille -> AC Milan",
  "dayot-upamecano": "Red Bull Salzburg -> RB Leipzig -> Bayern Munich",
  "kalidou-koulibaly": "Metz -> Genk -> Napoli -> Chelsea -> Al Hilal",
  "sadio-mane": "Metz -> Red Bull Salzburg -> Southampton -> Liverpool -> Bayern Munich -> Al Nassr",
  "edouard-mendy": "Reims -> Rennes -> Chelsea -> Al Ahli",
  "erling-haaland": "Bryne -> Molde -> Red Bull Salzburg -> Borussia Dortmund -> Manchester City",
  "martin-degaard": "Stromsgodset -> Real Madrid -> Real Sociedad -> Arsenal",
  "lionel-messi": "Barcelona academy -> Barcelona -> Paris Saint-Germain -> Inter Miami",
  "emiliano-martinez": "Independiente academy -> Arsenal -> Aston Villa",
  "enzo-fernandez": "River Plate -> Benfica -> Chelsea",
  "lautaro-martinez": "Racing Club -> Inter",
  "julian-alvarez": "River Plate -> Manchester City -> Atletico Madrid",
  "riyad-mahrez": "Le Havre -> Leicester City -> Manchester City -> Al Ahli",
  "david-alaba": "Austria Wien -> Bayern Munich -> Real Madrid",
  "cristiano-ronaldo": "Sporting CP -> Manchester United -> Real Madrid -> Juventus -> Manchester United -> Al Nassr",
  "bruno-fernandes": "Novara -> Udinese -> Sampdoria -> Sporting CP -> Manchester United",
  "bernardo-silva": "Benfica -> Monaco -> Manchester City",
  "diogo-costa": "Porto academy -> Porto",
  "ruben-dias": "Benfica -> Manchester City",
  "harry-kane": "Tottenham Hotspur academy -> Tottenham Hotspur -> Bayern Munich",
  "jude-bellingham": "Birmingham City -> Borussia Dortmund -> Real Madrid",
  "declan-rice": "West Ham United -> Arsenal",
  "bukayo-saka": "Arsenal academy -> Arsenal",
  "jordan-pickford": "Sunderland -> Everton",
  "josko-gvardiol": "Dinamo Zagreb -> RB Leipzig -> Manchester City",
  "luka-modric": "Dinamo Zagreb -> Tottenham Hotspur -> Real Madrid -> Milan",
  "mateo-kovacic": "Dinamo Zagreb -> Inter -> Real Madrid -> Chelsea -> Manchester City",
  "james-rodriguez": "Envigado -> Banfield -> Porto -> Monaco -> Real Madrid -> Bayern Munich -> Everton",
  "inaki-williams": "Athletic Club academy -> Athletic Club"
};

export const notableFactByPlayerId: Record<string, string> = {
  "kevin-de-bruyne": "Won the Champions League as part of Manchester City's 2022-23 treble-winning team.",
  "romelu-lukaku": "Became Belgium's record men's goalscorer before age 25.",
  "jeremy-doku": "Known for explosive one-v-one dribbling from wide areas.",
  "mohamed-salah": "Won both the Premier League and Champions League with Liverpool.",
  "omar-marmoush": "Breakout Bundesliga scoring form earned a major Premier League move.",
  "thibaut-courtois": "Won the Yashin Trophy after starring in Real Madrid's 2022 Champions League final win.",
  "youri-tielemans": "Scored the winning goal for Leicester City in the 2021 FA Cup final.",
  "bernardo-silva": "Won the Champions League as part of Manchester City's 2022-23 treble-winning team.",
  "bruno-fernandes": "Known for chance creation, penalties, and long-range shooting.",
  "cristiano-ronaldo": "Has scored at five different FIFA World Cups.",
  "jordan-pickford": "Saved penalties in major-tournament shootouts for England.",
  "neymar": "Won the Champions League with Barcelona in 2015.",
  "bruno-guimaraes": "Helped Newcastle return to the Champions League after a long absence.",
  "marquinhos": "Reached the 2020 Champions League final with Paris Saint-Germain.",
  "virgil-van-dijk": "Finished runner-up for the 2019 Ballon d'Or.",
  "wataru-endo": "Built a reputation as a ball-winning defensive midfielder in Germany and England.",
  "martin-degaard": "Made his senior Norway debut at age 15.",
  "riyad-mahrez": "Starred in Leicester City's 2015-16 Premier League title win.",
  "david-alaba": "Won multiple Champions League titles across Bayern Munich and Real Madrid.",
  "luka-modric": "Won the 2018 Ballon d'Or after leading Croatia to the World Cup final.",
  "darwin-nunez": "Earned a major European move after a prolific season with Benfica.",
  "trezeguet": "Scored twice for Egypt at the 2018 FIFA World Cup.",
  "jordan-ayew": "Comes from one of Ghana's most famous football families.",
  "anibal-godoy": "A long-serving leader from Panama's first World Cup generation."
};

export function getCareerPathOverride(player: Player): string | undefined {
  return careerPathByPlayerId[player.id];
}

export function getNotableFactOverride(player: Player): string | undefined {
  return notableFactByPlayerId[player.id];
}
